// lib/components/AddToCartButton.tsx
"use client";

import { useState } from "react";
import { ShoppingCart } from "lucide-react";

interface AddToCartButtonProps {
    productId: string;
    productName: string;
    disabled?: boolean;
}

export default function AddToCartButton({ productId, productName, disabled }: AddToCartButtonProps) {
    const [isLoading, setIsLoading] = useState(false);
    const [success, setSuccess] = useState(false);

    const handleAddToCart = async () => {
        setIsLoading(true);
        
        try {
            const response = await fetch("/api/cart", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ productId, quantity: 1 }),
            });

            if (response.ok) {
                setSuccess(true);
                setTimeout(() => setSuccess(false), 2000);
            } else {
                const errorData = await response.json();
                if (response.status === 401) {
                    // Redirect to sign in if not authenticated
                    window.location.href = "/sign-in";
                } else {
                    console.error("Failed to add to cart:", errorData.error);
                }
            }
        } catch (err) {
            console.error("Network error:", err);
        } finally {
            setIsLoading(false);
        }
    };

    if (success) {
        return (
            <button className="px-3 py-1 bg-green-500 text-white text-sm rounded-md transition-colors">
                Added!
            </button>
        );
    }

    return (
        <button 
            onClick={handleAddToCart}
            disabled={isLoading || disabled}
            className="px-3 py-1 bg-green-600 text-white text-sm rounded-md hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors flex items-center"
        >
            {isLoading ? (
                "Adding..."
            ) : (
                <>
                    <ShoppingCart className="h-3 w-3 mr-1" />
                    Add to Cart
                </>
            )}
        </button>
    );
}

// src/lib/components/AddToCartButton.svelte
<script lang="ts">
    const { listingId }: { listingId: string } = $props();

    let disabled = $state(false);

    function onclick(e: MouseEvent) {
        e.preventDefault();
        disabled = true;

        fetch(`/api/cart/add/${listingId}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            }
        })
        .then(response => {
            if (!response.ok) {
                disabled = false;
                throw new Error('Failed to add item to cart');
            }
            return response.json();
        })
        .then(data => {
            alert(data.message || data.error);
            disabled = false;
        });
    }
</script>

<button
    class="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-6 rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed"
    {onclick}
    {disabled}
>
    Add to Cart
</button>
